"""updated rental model

Revision ID: 1ec49f49e223
Revises: d2a4f37a624f
Create Date: 2021-11-14 12:04:16.086247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ec49f49e223'
down_revision = 'd2a4f37a624f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rentals', 'videos_checked_out')
    op.drop_column('rentals', 'available_inventory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentals', sa.Column('available_inventory', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('rentals', sa.Column('videos_checked_out', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
