"""fixed rental model

Revision ID: b34f942ac597
Revises: 104391cc0a9a
Create Date: 2021-11-10 18:17:06.382974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b34f942ac597'
down_revision = '104391cc0a9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rentals',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('customer_id', 'video_id')
    )
    op.drop_table('rental')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rental',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='rental_customer_id_fkey'),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], name='rental_video_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='rental_pkey')
    )
    op.drop_table('rentals')
    # ### end Alembic commands ###
