"""updated rental model to add to_json function

Revision ID: d2a4f37a624f
Revises: b34f942ac597
Create Date: 2021-11-12 12:13:19.595706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2a4f37a624f'
down_revision = 'b34f942ac597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentals', sa.Column('available_inventory', sa.Integer(), nullable=True))
    op.add_column('rentals', sa.Column('checked_out', sa.Boolean(), nullable=True))
    op.add_column('rentals', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('rentals', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('rentals', sa.Column('videos_checked_out', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rentals', 'videos_checked_out')
    op.drop_column('rentals', 'id')
    op.drop_column('rentals', 'due_date')
    op.drop_column('rentals', 'checked_out')
    op.drop_column('rentals', 'available_inventory')
    # ### end Alembic commands ###
